Wordpress compatibility
antistatique/docker-php-dev pull request #3
Opened 2019-04-03 13:58 UTC by yannlugrin

2020-12-07 13:36 UTC, gido requested changes

2020-12-07 13:36 UTC, gido commented on scripts/docker-as-wordpress
> +    --with-default-content   # Load default content (force reset database)
```suggestion
```

Option not used

2020-12-07 14:55 UTC, gido approved these changes

2020-12-07 15:05 UTC, gido commented
@yannlugrin good for me ! (only waiting on github actions about the tests result)

2020-12-24 12:41 UTC, yannlugrin commented
We have to update this PR with new tests and publish suit before merging.

2021-01-05 08:44 UTC, gido approved these changes

2021-01-05 08:44 UTC, merged